package com.deepcam.access.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.deepcam.access.entity.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Long> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "USERNAME");
        public final static Property EmployeeNumber = new Property(2, String.class, "employeeNumber", false, "EMPLOYEE_NUMBER");
        public final static Property Sector = new Property(3, String.class, "sector", false, "SECTOR");
        public final static Property FacePath = new Property(4, String.class, "facePath", false, "FACE_PATH");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property Feature = new Property(6, String.class, "feature", false, "FEATURE");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USERNAME\" TEXT," + // 1: name
                "\"EMPLOYEE_NUMBER\" TEXT," + // 2: employeeNumber
                "\"SECTOR\" TEXT," + // 3: sector
                "\"FACE_PATH\" TEXT," + // 4: facePath
                "\"GENDER\" TEXT," + // 5: gender
                "\"FEATURE\" TEXT NOT NULL );"); // 6: feature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String employeeNumber = entity.getEmployeeNumber();
        if (employeeNumber != null) {
            stmt.bindString(3, employeeNumber);
        }
 
        String sector = entity.getSector();
        if (sector != null) {
            stmt.bindString(4, sector);
        }
 
        String facePath = entity.getFacePath();
        if (facePath != null) {
            stmt.bindString(5, facePath);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
        stmt.bindString(7, entity.getFeature());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String employeeNumber = entity.getEmployeeNumber();
        if (employeeNumber != null) {
            stmt.bindString(3, employeeNumber);
        }
 
        String sector = entity.getSector();
        if (sector != null) {
            stmt.bindString(4, sector);
        }
 
        String facePath = entity.getFacePath();
        if (facePath != null) {
            stmt.bindString(5, facePath);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
        stmt.bindString(7, entity.getFeature());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // employeeNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sector
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // facePath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gender
            cursor.getString(offset + 6) // feature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmployeeNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSector(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFacePath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFeature(cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
